######################################################################
# Automatically generated by qmake (3.0) czw. kwi 24 01:56:41 2014
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += Resource \
           SharedData \
           String \
           SubStreams \
           Tokenizer \
           TokenParser \
           TurtleParser \
           Variant
